### PR TITLE
Updates main UI sizing for larger screens.

### PR DESCRIPTION
**Pull request by cedricwaxwing**
This update better accommodates larger screens (ex: Macbook 16" screen) so that the main content is always visible in the screen.

Current:
image

Updated:
image

### CODE REVIEW

**Review by samepant — CHANGES_REQUESTED** [review]
Nice! Although I'm seeing some mis-alignment with the 3 picker components at some aspect ratios. 

Screen Shot 2022-07-20 at 4 11 35 PM


This has me wondering if there is potential for a layout adjustment, since we are encouraging desktop use. It seems like we could move the two side UI components up and around the card image, increasing the potential size of them (those central buttons are really small). It would be sizable effort, as the gilding would have to be adjusted as well.

**Comment by cedricwaxwing** [comment]
Ah nice catch. I am assuming it's due to the aspect ratio not being exactly the same as the proportions of the image (there were decimals) - I'm going to see if there's a way I can do it without the aspect ratio property.

Good point!
I was experimenting a bit with it this morning. Thoughts on something like this?
image

**Comment by samepant** [comment]
wow this looks incredible, im obsessed

**Comment by samepant** [comment]
Added the new center gilding and rebased to master. 
Screen Shot 2022-07-25 at 3 25 16 PM

**Review by samepant — APPROVED** [review]

**Pull request merged**
